/**
 * Title:        PlottableData
 * Description:  Envelope for data generated by Python to be plottable (see PlottableData)
 * Copyright:    Copyright (c) 2002-8
 * Company:      OPeNDAP.org
 * @author       John Chamberlain
 * @version      3.02
 */

package opendap.clients.odc.plot;

public class PlottableExpression {

}
