/*
 * VariableSelector.java
 *
 * Created on December 21, 2001, 8:52 PM
 * Root of DDX/CE panel creation
 */

package opendap.clients.odc;

import java.lang.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.net.*;
import java.io.*;
import opendap.dap.*;

/**
 * This is the base class for the classes used by CEGenerator to make
 * a form to allow the user to constrain the data.
 *
 * @author Rich Honhart <rhonhart@virginia.edu>, John Chamberlain <info@johnchamberlain.com>
 */
public abstract class VariableSelector extends JPanel {

	private final static String ENCODING = "UTF-8";

    private boolean mzSelected;
    private JCheckBox checkSelection;

	protected JPanel mpanelHeader; // the name and checkbox
	protected JPanel mpanelDescription; // DAS description
	protected JPanel mpanelDetail; // the dimensions for grids/arrays
	private JLabel mlabelTitle;
	private JTextArea mjtaDescripton;

	protected DDSSelector mOwner;
	protected String msQualifiedName;

    /** Creates a new instance of VariableSelector */
    public VariableSelector( DDSSelector owner, String sQualifiedName ) {

		mOwner = owner;
		msQualifiedName = sQualifiedName;

		// selection check box
        checkSelection = new JCheckBox();
		checkSelection.setOpaque(false);
		checkSelection.addActionListener(
			new ActionListener(){
				public void actionPerformed(ActionEvent event) {
					setSelected( checkSelection.isSelected() );
				}
			}
		);

        mzSelected = true;
		setBackground(Color.WHITE);

		// setup header
		mpanelHeader = new JPanel();
		mlabelTitle = new JLabel();
		mpanelHeader.setOpaque(false);
		mlabelTitle.setOpaque(false);
		mpanelHeader.setLayout( new BoxLayout(mpanelHeader, BoxLayout.X_AXIS) );
		mpanelHeader.add( checkSelection );
		mpanelHeader.add( mlabelTitle );
		mpanelHeader.add( Box.createHorizontalGlue() );

		mpanelDescription = new JPanel();
		mpanelDescription.setOpaque(false);
		mpanelDescription.setVisible(false);
		mjtaDescripton = new JTextArea();
		mpanelDescription.setLayout( new BorderLayout() );
		mpanelDescription.add( mjtaDescripton, BorderLayout.CENTER );

		mpanelDetail = new JPanel();
		mpanelDetail.setOpaque(false);
		mpanelDetail.setVisible(false);

		setLayout( new BoxLayout(this, BoxLayout.Y_AXIS) );
		add(mpanelHeader);
		add(mpanelDescription);
		add(mpanelDetail);

    }

	void setTitle( String sTitle ){
		if( sTitle == null ) sTitle = "";
		mlabelTitle.setText( sTitle );
	}

	void setDescription( String sDescription ){
		if( sDescription == null ) sDescription = "";
		mjtaDescripton.setText( sDescription );
	}

	void vShowDescription( boolean zShow ){
		if( mjtaDescripton.getText() == null ){
			mpanelDescription.setVisible( false );
			return;
		}
		if( mjtaDescripton.getText().length() == 0 ){
			mpanelDescription.setVisible( false );
			return;
		}
		mpanelDescription.setVisible( zShow );
	}

	DDSSelector getOwner(){ return mOwner; }

    /**
     * Update the components on the screen to match a given constraint
     * expression.  This function does not work with any Dods compatible
     * constraint expression, only the subset that can be generated by
     * generateCE().
     * @param ce The constraint expression.
     */
    public void applyCE(String ce) {
	// If a specialization doesn't overload this function,
	// it is assumed that it has no components which need to be
	// updated, so this is left empty.
    }

    /**
     * Deselect this variable selector and all it's children.
     */
    public void deselectAll() {
        setSelected(false);
    }

    /**
     * Reset the everything in this <code>VariableSelector</code> and
     * all it's children.
     */
    public void reset() {
		setSelected(true);
    }

	final public String getQualifiedName(){
		return msQualifiedName;
	}

    /**
     * Return the radiobutton connected to the VariableSelector
     */
    public JCheckBox getButton() {
        return checkSelection;
    }

    /**
     * Generate a DODS constraint expression for the variable.
     * @param prefix Anything that needs to come before the constraint
     *               expression.  This is usually a Structure, Sequence,
     *               or other container class.  If a '.' is needed between
     *               the prefix and the part of the CE this class generates,
     *               it must be included at the end of the prefix.
     * @return a DODS constraint expression that will return the variable
     *         represented by this VariableSelector.
     */
    public String generateCE_Projection(String prefix) {
        return "";
    }

    public String generateCE_Selection(String prefix) {
        return "";
    }

    /**
     * @return Whether or not this VariableSelector is selected.
     *         (whether or not it should be included in a generated CE)
     */
    public boolean isSelected() {
        return mzSelected;
    }

	abstract public void vUpdateInfo( boolean zShowDetails );
	abstract public void vUpdateStep( int iStep );
	abstract public boolean hasStep();

	public void vUpdateSelection(){
		setSelected( checkSelection.isSelected() );
	}

    /**
     * Select or deselect the VariableSelector.  (Select the associated
     * button, and enable or disable the selector itself).
     * @param select Select(true) or Deselect(false).
     */
	boolean mzSettingSelected = false; // todo remove
    public void setSelected( boolean z ) {
		if( mzSettingSelected ){
			System.out.println("system error recursive, already setting selected");
			Thread.dumpStack();
			return;
		}
		mzSettingSelected = true;
        mzSelected = z;
		boolean zShowDescriptions = getOwner().mGenerator.zShowDescriptions();
		vUpdateInfo(zShowDescriptions);
		mpanelDetail.setVisible( z );

		// Whenever a selection is changed the subset is updated
		// the reason for this is that if the user selects just a map vector then
		// the "data" returned will the scale of vector. By selecting such
		// a vector is the only way to get the scale of a mapped dimension
		if( ApplicationController.getInstance().isConstraintChanging() ){
			// this is not a user change--the system is updating the radio button
		} else {
			ApplicationController.getInstance().getRetrieveModel().vUpdateSubset();
		}
		mzSettingSelected = false;
    }
}




